USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS RETAIL_OMNICHANNEL DATA_RETENTION_TIME_IN_DAYS = 7;
CREATE SCHEMA IF NOT EXISTS RETAIL_OMNICHANNEL.RAW DATA_RETENTION_TIME_IN_DAYS = 3;
CREATE SCHEMA IF NOT EXISTS RETAIL_OMNICHANNEL.CURATED DATA_RETENTION_TIME_IN_DAYS = 7;
CREATE SCHEMA IF NOT EXISTS RETAIL_OMNICHANNEL.AI DATA_RETENTION_TIME_IN_DAYS = 14;
CREATE SCHEMA IF NOT EXISTS RETAIL_OMNICHANNEL.ML DATA_RETENTION_TIME_IN_DAYS = 14;
CREATE SCHEMA IF NOT EXISTS RETAIL_OMNICHANNEL.APP;
CREATE WAREHOUSE IF NOT EXISTS WH_OMNICHANNEL WAREHOUSE_SIZE = 'MEDIUM' AUTO_SUSPEND = 120 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
