USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_OMNICHANNEL;
USE WAREHOUSE WH_OMNICHANNEL;

CREATE STAGE IF NOT EXISTS RETAIL_OMNICHANNEL.RAW.CLICKSTREAM_STAGE
    URL = 's3://sg-retail-demos-2026/omnichannel/clickstream/'
    STORAGE_INTEGRATION = RETAIL_DEMOS_S3_INTEGRATION
    FILE_FORMAT = (TYPE = 'JSON' STRIP_OUTER_ARRAY = TRUE);

CREATE NETWORK RULE IF NOT EXISTS RETAIL_OMNICHANNEL.AI.BEDROCK_NETWORK_RULE
    TYPE = HOST_PORT MODE = EGRESS VALUE_LIST = ('bedrock-runtime.us-west-2.amazonaws.com:443');
CREATE SECRET IF NOT EXISTS RETAIL_OMNICHANNEL.AI.BEDROCK_SECRET
    TYPE = GENERIC_STRING SECRET_STRING = '{}';
CREATE EXTERNAL ACCESS INTEGRATION IF NOT EXISTS RETAIL_OMNICHANNEL_BEDROCK_EAI
    ALLOWED_NETWORK_RULES = (RETAIL_OMNICHANNEL.AI.BEDROCK_NETWORK_RULE)
    ALLOWED_AUTHENTICATION_SECRETS = (RETAIL_OMNICHANNEL.AI.BEDROCK_SECRET)
    ENABLED = TRUE;
